package logviewer

import (
	"runtime"
	"testing"

	"github.com/bevicted/lognav/internal/deps/depstest"
	"github.com/bevicted/lognav/internal/filter"
	"github.com/bevicted/lognav/internal/icl"
	"github.com/bevicted/lognav/internal/ui/msgs"
)

// BenchmarkStore_Resident1M measures the resident heap of a fully loaded
// 1 M-row LogStore after a GC cycle.  Run with -benchtime 1x (one
// iteration) since the metric is a point-in-time heap snapshot, not a
// throughput rate.  The benchmark is the §6 gate: if HeapInuse after
// loading 1 M rows stays RAM-bounded (< a few hundred MB) we keep the
// all-in-memory design; if it exceeds the process limit we open a
// paged-store spec.  NOTE: the FINAL gate decision is made against a
// REAL collected >50 k archive; these synthetic numbers establish the
// baseline shape.
func BenchmarkStore_Resident1M(b *testing.B) {
	b.ReportAllocs()
	// Build the 1 M log corpus once; it is immutable input reused across
	// iterations (with -benchtime 1x there is only one).
	logs := newBenchLogs(b, 1_000_000)
	b.ResetTimer()
	for b.Loop() {
		// NewLogStore with depstest.NewTest(b) yields state.New() zero values
		// (JQ="", Search="", no Filters), so SetLogsRaw hits ApplyJQ's
		// empty-query early-return and DoSearch's nil-poster guard without ever
		// calling poster.Go — nil poster is safe.
		s := NewLogStore(depstest.NewTest(b), nil, "bench-1m")
		s.SetLogsRaw(logs)
		// Force a full GC so HeapInuse reflects live objects only, not
		// allocations that the mutator has already unreachable-d.
		runtime.GC()
		var ms runtime.MemStats
		runtime.ReadMemStats(&ms)
		b.ReportMetric(float64(ms.HeapInuse)/(1024*1024), "resident_MB")
		runtime.KeepAlive(s)
		if err := s.Close(); err != nil {
			b.Logf("BenchmarkStore_Resident1M: Close: %v", err)
		}
	}
}

// BenchmarkStore_Search1M measures the full search dispatch + compute at
// 1 M rows.  fakePoster runs chunk workers inline (synchronously) so
// DoSearch() returns only after every chunk has finished.  The loaded
// corpus is rebuilt per iteration (StopTimer) to avoid cumulative state
// across b.N runs; at -benchtime 1x this adds no overhead.
//
//nolint:dupl // structurally similar to BenchmarkStore_JQApply1M but exercises the search path (DoSearch/HandleSearchChunk) with different state mutations (SetSearch vs SetJQ) and different chunk types
func BenchmarkStore_Search1M(b *testing.B) {
	b.ReportAllocs()
	// Build the corpus once; immutable, shared across iterations.
	logs := newBenchLogs(b, 1_000_000)
	// "event" is a word present in every log line generated by
	// randomBenchPayload ("event %d at offset %d") so it reliably matches
	// across the full corpus and exercises all search-chunk workers.
	const searchTerm = "event"
	b.ResetTimer()
	for b.Loop() {
		// Rebuild a fresh store each iteration so result maps do not carry
		// forward stale entries from prior iterations.
		b.StopTimer()
		bundle := depstest.NewTest(b)
		s := NewLogStore(bundle, nil, "bench-search-1m")
		fp := &fakePoster{}
		s.SetPoster(fp)
		s.SetLogsRaw(logs)
		// Clear any chunks posted by SetLogsRaw's jq/filter passes (its DoSearch
		// runs with an empty query; wipe so the drain below is clean).
		fp.mu.Lock()
		fp.posted = fp.posted[:0]
		fp.mu.Unlock()
		bundle.State.SetSearch(searchTerm)
		b.StartTimer()

		// fakePoster.Go runs inline → DoSearch executes all chunk workers
		// synchronously before returning.  Drain chunks to apply results.
		s.DoSearch()
		for _, chunk := range fp.searchChunks() {
			s.HandleSearchChunk(chunk)
		}

		b.StopTimer()
		if err := s.Close(); err != nil {
			b.Logf("BenchmarkStore_Search1M: Close: %v", err)
		}
		b.StartTimer()
	}
}

// BenchmarkStore_FilterApply1M measures ApplyFilters over 1 M rows.
// ApplyFilters is synchronous (no poster involvement), so the timing is
// the raw hide-decision compute for the full corpus.  A term-Include rule
// is used (Aho-Corasick path, the common case).
func BenchmarkStore_FilterApply1M(b *testing.B) {
	b.ReportAllocs()
	logs := newBenchLogs(b, 1_000_000)
	// Include rule: keep only logs containing "error".  ~10% of lines will
	// be visible (those with severity Warning+ or whose msg happens to
	// include the word); the rest are hidden.  The exact hit rate does not
	// affect the benchmark — every log is evaluated.
	rules := []filter.Rule{{Type: filter.Include, Value: "error"}}
	b.ResetTimer()
	for b.Loop() {
		b.StopTimer()
		bundle := depstest.NewTest(b)
		s := NewLogStore(bundle, nil, "bench-filter-1m")
		s.SetPoster(&fakePoster{})
		s.SetLogsRaw(logs)
		bundle.State.SetFilters(rules)
		b.StartTimer()

		// ApplyFilters is synchronous; no chunks to drain.
		s.ApplyFilters()

		b.StopTimer()
		if err := s.Close(); err != nil {
			b.Logf("BenchmarkStore_FilterApply1M: Close: %v", err)
		}
		b.StartTimer()
	}
}

// BenchmarkStore_JQApply1M measures the full jq dispatch + compute at
// 1 M rows.  fakePoster runs chunk workers inline so ApplyJQ() returns
// only after every chunk has finished.  The expression ".msg" is a
// shallow field select present on every synthetic log record.
//
//nolint:dupl // structurally similar to BenchmarkStore_Search1M but exercises the jq path (ApplyJQ/HandleJQChunk) with different state mutations (SetJQ vs SetSearch) and different chunk types
func BenchmarkStore_JQApply1M(b *testing.B) {
	b.ReportAllocs()
	logs := newBenchLogs(b, 1_000_000)
	const jqExpr = ".msg"
	b.ResetTimer()
	for b.Loop() {
		b.StopTimer()
		bundle := depstest.NewTest(b)
		s := NewLogStore(bundle, nil, "bench-jq-1m")
		fp := &fakePoster{}
		s.SetPoster(fp)
		s.SetLogsRaw(logs)
		fp.mu.Lock()
		fp.posted = fp.posted[:0]
		fp.mu.Unlock()
		bundle.State.SetJQ(jqExpr)
		b.StartTimer()

		// fakePoster.Go runs inline → ApplyJQ executes all chunk workers
		// synchronously before returning.  Drain chunks to apply results.
		s.ApplyJQ()
		for _, chunk := range fp.jqChunks() {
			s.HandleJQChunk(chunk)
		}

		b.StopTimer()
		if err := s.Close(); err != nil {
			b.Logf("BenchmarkStore_JQApply1M: Close: %v", err)
		}
		b.StartTimer()
	}
}

// BenchmarkStore_StreamIngestOnLoop1M measures the ON-LOOP ingest cost of a
// 1 M-row stream with jq, filter rules and search all active: everything
// HandleLogStreamMsg → dispatchPendingBatches → spawn* (and the
// HandleJQChunk-sequenced filter/re-search) does on the loop goroutine before a
// chunk reaches a worker.  dropPoster discards the worker bodies, so the number
// is the loop's share of ingest alone — the quantity per-epoch compile caching
// targets (ticket 06 / audit item 12).  The jq worker's reply is synthesized so
// the measurement is not swamped by a million gojq evaluations.
func BenchmarkStore_StreamIngestOnLoop1M(b *testing.B) {
	b.ReportAllocs()
	const (
		rows  = 1_000_000
		batch = 2000
	)
	// One shared, immutable data map per row: entry data is never mutated in
	// place and the dropped workers never read it concurrently.
	data := map[string]any{"msg": "event happened"}
	logs := make([]icl.Log, batch)
	for i := range logs {
		logs[i] = icl.Log{Data: data, Metadata: icl.Metadata{TSMicro: int64(i)}}
	}
	results := make([]any, batch)
	for i := range results {
		results[i] = "event happened"
	}
	rules := []filter.Rule{
		{Type: filter.Include, Value: "event"},
		{Type: filter.HasField, Value: ".msg"},
	}
	b.ResetTimer()
	for b.Loop() {
		b.StopTimer()
		bundle := depstest.NewTest(b)
		bundle.State.SetJQ(".msg")
		bundle.State.SetSearch("event")
		bundle.State.SetFilters(rules)
		s := NewLogStore(bundle, nil, "bench-ingest-1m")
		s.SetPoster(dropPoster{})
		s.StartStream(rows)
		b.StartTimer()

		for k := range rows / batch {
			s.HandleLogStreamMsg(&msgs.LogStreamMsg{ID: s.GetQueryID(), Logs: logs})
			s.HandleJQChunk(JQChunkMsg{Instance: "bench-ingest-1m", ID: s.GetQueryID(), Offset: k, Results: results})
		}
		s.HandleLogStreamDoneMsg(&msgs.LogStreamDoneMsg{ID: s.GetQueryID()})

		b.StopTimer()
		if err := s.Close(); err != nil {
			b.Logf("BenchmarkStore_StreamIngestOnLoop1M: Close: %v", err)
		}
		b.StartTimer()
	}
}
